import Head from 'next/head'
import Banner from '@/layouts/home/Banner'
import ProductsGrid from '@/layouts/home/ProductsGrid'
import Technologies from '@/layouts/home/Technologies'
import Reviews from '@/layouts/home/Reviews'
import CallToAction from '@/layouts/home/CallToAction'
import ProductsSlider from '@/layouts/home/ProductsSlider'
import Faqs from '@/layouts/home/Faqs'
import CommonLayout from '@/layouts/common/CommonLayout'

export default function Home() {
    return (
        <>
            <Head>
                <title>Frontend Template</title>
                <meta charset="UTF-8" />
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <CommonLayout>
                <Banner />
                <ProductsGrid />
                <Technologies />
                <Reviews />
                <CallToAction />
                <ProductsSlider />
                <Faqs />
            </CommonLayout>
        </>
    )
}
